// Generated by https://quicktype.io

export interface ClientResponse {
    encodedKey:        string;
    id:                string;
    state:             string;
    creationDate:      string;
    lastModifiedDate:  string;
    activationDate:    string;
    approvedDate:      string;
    firstName:         string;
    lastName:          string;
    middleName:        string;
    homePhone:         string;
    mobilePhone:       string;
    emailAddress:      string;
    preferredLanguage: string;
    birthDate:         string;
    gender:            string;
    notes:             string;
    clientRoleKey:     string;
    loanCycle:         number;
    groupLoanCycle:    number;
    groupKeys:         string[];
    addresses:         Address[];
    idDocuments:       IDDocument[];
    _PEP:              Pep;
}

export interface Pep {
    IS_PEP: string;
}

export interface Address {
    encodedKey:  string;
    parentKey:   string;
    line1:       string;
    line2:       string;
    city:        string;
    region:      string;
    postcode:    string;
    country:     string;
    indexInList: number;
}

export interface IDDocument {
    encodedKey:       string;
    clientKey:        string;
    documentType:     string;
    documentId:       string;
    issuingAuthority: string;
    indexInList:      number;
}


